#!/bin/bash

A_BUTTON="01111111"
B_BUTTON="10111111"
SELECT_BUTTON="11011111"
START_BUTTON="11101111"
UP_BUTTON="11110111"
DOWN_BUTTON="11111011"
LEFT_BUTTON="11111101"
RIGHT_BUTTON="11111110"

#larger value will decrease sensitivity of controller
DELAY=0.00005

#clock
echo "14" > /sys/class/gpio/unexport
#latch
echo "15" > /sys/class/gpio/unexport
#data
echo "18" > /sys/class/gpio/unexport

#light (optional)
echo "7" > /sys/class/gpio/unexport

#clock
echo "14" > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio14/direction
#latch
echo "15" > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio15/direction

#data
echo "18" > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio18/direction

#clock
echo "1" > /sys/class/gpio/gpio14/value
#latch
echo "1" > /sys/class/gpio/gpio15/value

#light (optional)
echo "7" > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio7/direction
echo "0" > /sys/class/gpio/gpio7/value

while (true)
do
    #turn latch on and then off to start collecting data
    echo "1" > /sys/class/gpio/gpio15/value
    sleep $DELAY
    echo "0" > /sys/class/gpio/gpio15/value
    #get leading bit data and append to OLDVAL
    NEWVAL=`cat /sys/class/gpio/gpio18/value` 
    OLDVAL=$OLDVAL$NEWVAL
    #for next seven bits do
    for VARIABLE in  1 2 3 4 5 6 7
   	do
        #turn clock tick on
        echo "1" > /sys/class/gpio/gpio14/value
        #get data, append to previous bits
        NEWVAL=`cat /sys/class/gpio/gpio18/value` 
        OLDVAL=$OLDVAL$NEWVAL
        sleep $DELAY
        #turn clock tick off
        echo "0" > /sys/class/gpio/gpio14/value
        sleep $DELAY
	done
       
       #compare the resulting bits to known button values
       if [ "$OLDVAL" = "$A_BUTTON" ]; then
                 echo "A BUTTON"
                 #turn light on (optional)
                 echo "1" > /sys/class/gpio/gpio7/value
       fi

 	if [ "$OLDVAL" =  "$B_BUTTON" ]; then
                 echo "B BUTTON"
                 #turn light off (optional)
                 echo "0" > /sys/class/gpio/gpio7/value
       fi
        
       if [ "$OLDVAL" =  "$SELECT_BUTTON" ]; then
                 echo "SELECT BUTTON"
       fi
        
       if [ "$OLDVAL" =  "$START_BUTTON" ]; then
                 echo "START BUTTON"
       fi
        
       if [ "$OLDVAL" =  "$UP_BUTTON" ]; then
                 echo "UP"
       fi
        
       if [ "$OLDVAL" =  "$DOWN_BUTTON" ]; then
                 echo "DOWN"
       fi
        
       if [ "$OLDVAL" =  "$LEFT_BUTTON" ]; then
                 echo "LEFT"
       fi
        
       if [ "$OLDVAL" =  "$RIGHT_BUTTON" ]; then
                 echo "RIGHT"
       fi

       #clear OLDVAL value for next button press
       OLDVAL=''
done