#!/bin/bash

A_BUTTON="01111111"
B_BUTTON="10111111"
SELECT_BUTTON="11011111"
START_BUTTON="11101111"
UP_BUTTON="11110111"
DOWN_BUTTON="11111011"
LEFT_BUTTON="11111101"
RIGHT_BUTTON="11111110"
UP_LEFT="11110101"
UP_RIGHT="11110110"
DOWN_LEFT="11111001"
DOWN_RIGHT="11111010"
A_B="00111111"

A_START=""
A_SELECT=""
A_RIGHT="01111110"
A_LEFT="01111101"
A_UP="01110111"
A_DOWN="01111011"
A_UP_LEFT="01110101"
A_UP_RIGHT="01110110"
A_DOWN_LEFT="01111001"
A_DOWN_RIGHT="01111010"

B_START=""
B_SELECT=""
B_RIGHT="10111110"
B_LEFT="10111101"
B_UP="10110111"
B_DOWN="10111011"
B_UP_LEFT="10110101"
B_UP_RIGHT="10110110"
B_DOWN_LEFT="10111001"
B_DOWN_RIGHT="10111010"



#larger value will decrease sensitivity of controller
DELAY=0.0000005

#clock
echo "14" > /sys/class/gpio/unexport
#latch
echo "15" > /sys/class/gpio/unexport
#data
echo "18" > /sys/class/gpio/unexport

#light (optional)
echo "7" > /sys/class/gpio/unexport

#clock
echo "14" > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio14/direction
#latch
echo "15" > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio15/direction

#data
echo "18" > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio18/direction

#clock
echo "1" > /sys/class/gpio/gpio14/value
#latch
echo "1" > /sys/class/gpio/gpio15/value

#light (optional)
echo "7" > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio7/direction
echo "0" > /sys/class/gpio/gpio7/value

while (true)
do
    #turn latch on and then off to start collecting data
    echo "1" > /sys/class/gpio/gpio15/value
    sleep $DELAY
    echo "0" > /sys/class/gpio/gpio15/value
    #get leading bit data and append to OLDVAL
    NEWVAL=`cat /sys/class/gpio/gpio18/value` 
    OLDVAL=$OLDVAL$NEWVAL
    #for next seven bits do
    for VARIABLE in  1 2 3 4 5 6 7
   	do
        #turn clock tick on
        echo "1" > /sys/class/gpio/gpio14/value
        #get data, append to previous bits
        NEWVAL=`cat /sys/class/gpio/gpio18/value` 
        OLDVAL=$OLDVAL$NEWVAL
        sleep $DELAY
        #turn clock tick off
        echo "0" > /sys/class/gpio/gpio14/value
        sleep $DELAY
	done
 
       #output bits for debugging
       #echo $OLDVAL
       
       #compare the resulting bits to known button values
       if [ "$OLDVAL" = "$A_BUTTON" ]; then
                 echo "A"
                 #turn light on (optional)
                 echo "1" > /sys/class/gpio/gpio7/value
       fi

 	if [ "$OLDVAL" =  "$B_BUTTON" ]; then
                 echo "B"
                 #turn light off (optional)
                 echo "0" > /sys/class/gpio/gpio7/value
       fi
        
       if [ "$OLDVAL" =  "$SELECT_BUTTON" ]; then
                 echo "SELECT BUTTON"
       fi
        
       if [ "$OLDVAL" =  "$START_BUTTON" ]; then
                 echo "START BUTTON"
       fi
        
       if [ "$OLDVAL" =  "$UP_BUTTON" ]; then
                 echo "UP"
       fi
        
       if [ "$OLDVAL" =  "$DOWN_BUTTON" ]; then
                 echo "DOWN"
       fi
        
       if [ "$OLDVAL" =  "$LEFT_BUTTON" ]; then
                 echo "LEFT"
       fi
        
       if [ "$OLDVAL" =  "$RIGHT_BUTTON" ]; then
                 echo "RIGHT"
       fi

       if [ "$OLDVAL" =  "$UP_LEFT" ]; then
                 echo "UP LEFT"
       fi

	if [ "$OLDVAL" =  "$UP_RIGHT" ]; then
                 echo "UP RIGHT"
       fi

	if [ "$OLDVAL" =  "$DOWN_LEFT" ]; then
                 echo "DOWN LEFT"
       fi

	if [ "$OLDVAL" =  "$DOWN_RIGHT" ]; then
                 echo "DOWN RIGHT"
       fi

	if [ "$OLDVAL" =  "$A_RIGHT" ]; then
                 echo "A RIGHT"
       fi

	if [ "$OLDVAL" =  "$A_LEFT" ]; then
                 echo "A LEFT"
       fi

	if [ "$OLDVAL" =  "$A_UP" ]; then
                 echo "A UP"
       fi

	if [ "$OLDVAL" =  "$A_DOWN" ]; then
                 echo "A DOWN"
       fi

	if [ "$OLDVAL" =  "$A_UP_LEFT" ]; then
                 echo "A UP LEFT"
       fi

	if [ "$OLDVAL" =  "$A_UP_RIGHT" ]; then
                 echo "A UP RIGHT"
       fi

	if [ "$OLDVAL" =  "$A_DOWN_LEFT" ]; then
                 echo "A DOWN LEFT"
       fi

	if [ "$OLDVAL" =  "$A_DOWN_RIGHT" ]; then
                 echo "A DOWN RIGHT"
       fi

       if [ "$OLDVAL" =  "$B_RIGHT" ]; then
                 echo "B RIGHT"
       fi

	if [ "$OLDVAL" =  "$B_LEFT" ]; then
                 echo "B LEFT"
       fi

	if [ "$OLDVAL" =  "$B_UP" ]; then
                 echo "B UP"
       fi

	if [ "$OLDVAL" =  "$B_DOWN" ]; then
                 echo "B DOWN"
       fi

	if [ "$OLDVAL" =  "$B_UP_LEFT" ]; then
                 echo "B UP LEFT"
       fi

	if [ "$OLDVAL" =  "$B_UP_RIGHT" ]; then
                 echo "B UP RIGHT"
       fi

	if [ "$OLDVAL" =  "$B_DOWN_LEFT" ]; then
                 echo "B DOWN LEFT"
       fi

	if [ "$OLDVAL" =  "$B_DOWN_RIGHT" ]; then
                 echo "B DOWN RIGHT"
       fi



       #clear OLDVAL value for next button press
       OLDVAL=''
       #pause until keypress for debugging
       #read myvalue
done